# Generated by Django 5.1.7 on 2025-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("ready", "Готово"),
                    ("paid", "Оплачено"),
                ],
                default="waiting",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
